---

- name: Install dev packages
  package:
    name: '{{ dev_packages }}'
    state: present

- name: Create dev user
  user: 
    name: '{{ dev_user }}'
    shell: /bin/zsh

- name: Add authorized keys file
  authorized_key:
    user: '{{ dev_user }}'
    state: present
    key: '{{ item }}'
  with_items: "{{ authorized_keys }}"

- name: Start sshd service
  systemd:
    state: started
    name: sshd

- name: Install dotfile packages
  package:
    name: '{{ dotfile_packages }}'
    state: present

- name: Fetch dotfiles
  git:
    repo: https://github.com/lyrch/dotfiles.git
    dest: '/home/{{ dev_user }}/.dotfiles'

- name: Link dotfiles
  command: rcup -f -d '/home/{{ dev_user}}/.dotfiles'
