---
# tasks file for base-dev

- name: Install dev packages
  package:
    name: '{{ dev_packages }}'
    state: present

- name: Create dev user
  user: 
    name: '{{ dev_user }}'
    shell: /bin/zsh

- name: Add authorized keys file
  authorized_key:
    user: '{{ dev_user }}'
    state: present
    key: '{{ item }}'
  with_items: "{{ authorized_keys }}"

- name: Start sshd service
  systemd:
    state: started
    name: sshd
